//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Summarizer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));
        
        public static AppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("아무개")]
        public string StaffName {
            get {
                return ((string)(this["StaffName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("채널로 예약문자 전송")]
        public string ReservationConfirmMessage {
            get {
                return ((string)(this["ReservationConfirmMessage"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>상담받을 분의 성함 / 연락처 - </string>
  <string>생년월일 - </string>
  <string>상담부위 - </string>
  <string>첫수술or 재수술 (재수술일경우 마지막 수술시기 ) - </string>
  <string>상담 희망 날짜와 시간대 - </string>
  <string>상담 원하는 원장님 - </string>
  <string>저희 병원 알게되신 경로 - </string>
  <string>소개자 있으실 경우 소개자 성함과 연락처 뒷번호 - </string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection FormMessages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["FormMessages"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"">
  <string>안녕하세요~</string>
  <string>안녕하세요^^</string>
  <string>안녕하세요~^^</string>
  <string>^^</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SliceStaffMessages {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SliceStaffMessages"]));
            }
        }
    }
}
